"""Content curation, ranking, de-duplication, and source discovery."""

from app.curation.classification import (
    BucketConfig,
    Classification,
    classify_and_filter,
    classify_item,
    get_bucket_config,
    load_bucket_config,
)
from app.curation.curator import CurationResult, ScoredItem, curate_items
from app.curation.deduplication import (
    DeduplicationKey,
    content_hash,
    deduplicate_items,
    deduplication_keys,
    item_value,
    normalize_text,
    normalize_title,
    normalize_url,
)
from app.curation.ranking import (
    DEFAULT_KEYWORD_WEIGHTS,
    DEFAULT_SOURCE_TRUST_SCORE,
    DEFAULT_SOURCE_TRUST_SCORES,
    RankingScore,
    keyword_score,
    parse_datetime,
    rank_items,
    recency_score,
    score_item,
    score_item_breakdown,
    select_top_items,
    source_trust_score,
)
from app.curation.source_discovery import (
    SourceRegistry,
    demote_stale_sources,
    domain_of,
    dynamic_source_trust_map,
    harvest_candidates,
    load_registry,
    novelty_bonus,
    promote_candidates,
    record_dropped,
    record_posted,
    save_registry,
    seed_trusted,
)

__all__ = [
    "DEFAULT_KEYWORD_WEIGHTS",
    "DEFAULT_SOURCE_TRUST_SCORE",
    "DEFAULT_SOURCE_TRUST_SCORES",
    "BucketConfig",
    "Classification",
    "CurationResult",
    "DeduplicationKey",
    "RankingScore",
    "ScoredItem",
    "SourceRegistry",
    "classify_and_filter",
    "classify_item",
    "content_hash",
    "curate_items",
    "deduplicate_items",
    "deduplication_keys",
    "demote_stale_sources",
    "domain_of",
    "dynamic_source_trust_map",
    "get_bucket_config",
    "harvest_candidates",
    "item_value",
    "keyword_score",
    "load_bucket_config",
    "load_registry",
    "normalize_text",
    "normalize_title",
    "normalize_url",
    "novelty_bonus",
    "parse_datetime",
    "promote_candidates",
    "rank_items",
    "recency_score",
    "record_dropped",
    "record_posted",
    "save_registry",
    "score_item",
    "score_item_breakdown",
    "seed_trusted",
    "select_top_items",
    "source_trust_score",
]
